export default {

    BASE_URL_PATH:  'urlPath',
    
    EMP_ID: 'empId',
    BUDGETING_STATUS:  'budgetingStatus',
    LOCATION_NAME: 'locationName',
    MESSAGE: 'Message',
    DESIGNATION_ID: 'designationId',
    ORG_UNIT: 'orgUnit',
    PC_NAME: 'pcName',
    CC_NAME: 'ccName',
    TYPE: 'type',
    FOR_UNIT_ID: 'forUnitId',
    COMPANY_ID: 'companyId',
    PR_ROLE: 'prRole',
    CC_ID: 'ccId',
    ZONE: 'zone',
    LOCATION_ID: 'locationId',
    EMP_NAME: 'empName',
    UNIT_ID: 'unitId',
    ZONE_ID: 'zoneId',
    PC_ID: 'pcId',
    PROFIT_CENTER_ID : 'profitCenterId',
    PROFIT_CENTER_NAME : 'profitCenterName',
    COMPANY: 'company',
    DESIGNATION: 'designation',
    DET_FUND_ID:  'detFundId', 
    DET_FUND: 'detFund', 
    DET_PROJECT_ID: 'detProjectId',
    DET_PROJECT: 'detProject',
    DET_SUB_ACC_CODE: 'detSubAccCode',
    IS_PR_VISIBLE: 'isPRVisible',
    IS_ASSET_VISIBLE: 'isAssetPhysVerVisible',
    MODULE_TYPE: 'moduleType',
    PR_CREATE_ROLE: 'prCreateRole',
    USER_LOGIN_SUCCESS: 'userLoginSuccess',
    SHOW_INV_WITH_PO_LIST: 'showInvWithPOList',
    SHOW_INV_WITHOUT_PO_LIST: 'showInvWithoutPOList',

    APP_VERSION: 'appVersion',
    P2P_VERSION: 'p2pVersion',
    ASSET_VERSION: 'assetVersion',
    CONTACT: 'contact',

    IS_EXPENSE_ADDED:  'is_expense_added',

}